export const ARTIST_ADD_SUCCESS ="ARTIST_ADD_SUCCESS";
export const ARTIST_ADD_FAIL ="ARTIST_ADD_FAIL";

export const ARTIST_GET_SUCCESS ="ARTIST_GET_SUCCESS";
export const ARTIST_GET_FAIL ="ARTIST_GET_FAIL";


export const ARTIST_SUCESS_CLEAR ="ARTIST_SUCESS_CLEAR";
export const ARTIST_ERROR_CLEAR ="ARTIST_ERROR_CLEAR";