export const SONG_ADD_SUCCESS ="SONG_ADD_SUCCESS";
export const SONG_ADD_FAIL ="SONG_ADD_FAIL";

export const SONG_GET_SUCCESS ="SONG_GET_SUCCESS";
export const SONG_GET_FAIL ="SONG_GET_FAIL";

export const SONG_UPDATE_SUCCESS = "SONG_UPDATE_SUCCESS";
export const SONG_UPDATE_FAIL = "SONG_UPDATE_FAIL";


export const SONG_SUCESS_CLEAR ="SONG_SUCESS_CLEAR";
export const SONG_ERROR_CLEAR ="SONG_ERROR_CLEAR";